### ISSUE TITLE
Remove dependency on custom nginx build and ngx_cache_purge

### ISSUE THREAD

**Issue by doliver3** [rtCamp/nginx-helper#104]
Hi,

Could you remove the dependency on this third-party module which requires a custom nginx build?
https://github.com/FRiCKLE/ngx_cache_purge

This would make your plugin much easier to use.

The convention for the nginx fastcgi key is well known and understood. There is even a section in this popular article (link follows) about how to identify which key to delete in the fastcgi cache in the purging the cache section. 
https://www.digitalocean.com/community/tutorials/how-to-setup-fastcgi-caching-with-nginx-on-your-vps

The functionality of selectively deleting the cache keys could be provided without the dependency on the third-party module by asking the user for the key pattern in their nginx configuration on a wp-admin page and then calculating the key to delete on demand. 

Does this seem possible?

Thanks,
David

**Comment by rahul286** [comment]
There is an option to use md5 hash method without using ngx_cache_purge module.

![nginx_helper_ _rtcamp_ _wordpress](https://cloud.githubusercontent.com/assets/4115/9079329/9ab4b0f4-3b66-11e5-8fe0-a8b27597eb3b.png)

The key pattern can be passed by defining `RT_WP_NGINX_HELPER_CACHE_PATH` in `wp-config.php` file.
