### ISSUE TITLE
Call to a member function log() on a non-object

### ISSUE THREAD

**Issue by someblueuser** [rtCamp/nginx-helper#105]
After setting nginx-helper (1.9.5)  mode to Redis, it throws this error message, cannot active plugin again, even after deleting them with all files and installing again. My WP is v.4.3
"Fatal error: Call to a member function log() on a non-object in /wp-content/plugins/nginx-helper/includes/redis-delete.php on line 33"

**Comment by chandrapatel** [comment]
This issue has been fixed and closing now.
