### ISSUE TITLE
Nginx fastcgi_cahe - delete cache for a single site in multisite network

### ISSUE THREAD

**Issue by rahul286** [rtCamp/nginx-helper#11]
#### 2 ways to explore
1. Either use separate  `fastcgi_cache_path` per site
2. OR use a `http_host` name for  multisite name
3. OR keep cached-pages list per site on wordpress end (ugliest solution)

**Comment by chandrapatel** [comment]
Closing this issue as it's very old, no longer relevant, and no plan to support FastCGI cache.
