### ISSUE TITLE
Purge network home url when post is published.

### ISSUE THREAD

**Issue by mvirenius** [rtCamp/nginx-helper#110]
Hi,

Could it be possible to add option to purge network front page (network_home_url), when new post is published. Example function to be added to the Purger Class:

``` php
        private function _purge_network_homepage() {

            $network_homepage_url = trailingslashit( network_home_url() );

            $this->log( sprintf( __( "Purging network homepage '%s'", "nginx-helper" ), $network_homepage_url ) );
            $this->purgeUrl( $network_homepage_url );

            return true;
        }
```

Function could be called from purgePost method.

**Comment by mrrobot47** [comment]
Closing this is as it is a specific use case. We are not planning to add support for it as of now.
