### ISSUE TITLE
Purge Cache clears the whole Redis cache, of ALL the users/prefixes...

### ISSUE THREAD

**Issue by HansVanEijsden** [rtCamp/nginx-helper#113]
When one of my users installs the Nginx Helper (we even deploy it automatically on every new Wordpress installation) and clicks the Purge Cache button in the admin bar on top, it clears the **whole** Redis database...
All the page caches of all the users flushed, all the object caches of all the users gone, and Redis completely empty.

Imagine this. A 28GB Redis cache size, 800 users. One of those 800 users presses the Purge Cache button on top, and all the other 799 sites have to warm up the cache again. More than 28GB of cache data gone, every time one of those 800 users presses their button. That's a big problem.

Every site has an own prefix, "example.com:" in the Nginx config and in the Nginx Helper plugin.
I use this config: https://easyengine.io/wordpress-nginx/tutorials/single-site/redis_cache-with-conditional-purging/

Is there a way to make the Nginx Helper only purge "example.com:\*" from Redis when the user presses Purge Cache, in stead of "\*"?
And if not, is there an easy way to disable the Purge Cache button?

Thanks!

**Comment by Niwreg** [comment]
I did an [https://github.com/rtCamp/nginx-helper/pull/116](url) pull request that fixes this problem.

**Comment by larssn** [comment]
@Niwreg What happened to this pull request?

**Comment by HansVanEijsden** [comment]
@larssn would love to know that too, I still wait for the merge. Now I have to do all manual, because of the old version in the Wordpress svn.

**Comment by larssn** [comment]
@HansVanEijsden If you're using Redis as your caching layer, I made this fork, which fixes the problem, but only in Redis:
https://github.com/larssn/nginx-helper

**Comment by chandra-patel** [comment]
Hello @HansVanEijsden @Niwreg 

I am sorry for the late response. I have merged the PR and we are doing testing and will release new version soon.

Thanks.

**Comment by HansVanEijsden** [comment]
@larssn nice work. Is it any different from https://github.com/rtCamp/nginx-helper/pull/116 (which was already merged, but also not released yet)?

**Comment by larssn** [comment]
My code is based on the latest master branch.

Looking through the code of #116, it doesn't seem to have fixed what you initially asked. It seems related to WPML and another non-related issue.

For example, my fix makes a multisite running in subfolders work, which the previous did not take into account.

**Comment by HansVanEijsden** [comment]
@larssn now I see. Great, thanks for all!

**Comment by larssn** [comment]
Made #122

**Comment by chandra-patel** [comment]
Hello @HansVanEijsden 

I have released the plugin. Please check. Also I am closing this ticket. Thanks for your help.
