### ISSUE TITLE
Purge All is broking the website

### ISSUE THREAD

**Issue by thiagolcks** [rtCamp/nginx-helper#120]
Hi,

After I've run the Purge All I'm getting the error in all public pages (not logged in): mkdir() "/var/run/nginx-cache/temp/8" failed (2: No such file or directory)

If I restart the server it's all good. It seems that the Purge All is deleting the temp folder, and nginx is not creating the folder again, just when restarted.

I could fix it adding the following line to the file purger.php after the line 752:
`mkdir(RT_WP_NGINX_HELPER_CACHE_PATH . '/temp');`

I'm using nginx 1.11.3.

Thanks

**Comment by johan-chassaing** [comment]
Hi, 
I have actually the same issue.
Indeed, ngnix helper is removing all files and folders un nginx cache directory.
The restart of the nginx service give back the website.
From the nginx forum, I saw the purge should be done only on the files and not on the folders.

Johan

**Comment by johan-chassaing** [comment]
vim nginx-helper/purger.php +774
replace true per false 
 $this->unlinkRecursive( $dir . '/' . $obj, false );

**Comment by johan-chassaing** [comment]
#123

**Comment by chandra-patel** [comment]
Hello @johan-chassaing @thiagolcks 

I've accepted PR and will release update soon. Thanks. I'm closing this issue.

Regards,
Chandra

**Comment by chandra-patel** [comment]
Hello,

I've released new version 1.9.10. Please update the plugin. Thanks.
