### ISSUE TITLE
Purge forum index

### ISSUE THREAD

**Issue by Paike** [rtCamp/nginx-helper#126]
I tried to purge the forum index on topic change. It works when a topic post is deleted. I found the forum ID in the post's meta. But this is empty, when the post is just published / when Nginx Helper hooks.

``` php
    $topic_meta = get_post_meta($_post_ID);

    $str_meta = print_r($topic_meta, true);
    $this->log('Meta: '.$str_meta);
    $_forum_ID = $topic_meta['_bbp_forum_id'][0];
    $this->log('Post ID: ' .$_post_ID);
    $this->log('Forum ID: ' .$_forum_ID);
    $_purge_forum = true;

    if( $_purge_forum) {
        $this->log( "Purging forum index (topic id $_post_ID, forum id $_forum_ID)" );
        $this->purgeUrl( get_permalink( $_forum_ID ) );
    }
// purger.php:120 _purge_by_options()
```

Someone has an idea? The forum index states how many topics and posts exist in the forum, and when the last update was made. 

Another option would be to prevent caching of forum index. But maybe purging can be made possible.

**Comment by mrrobot47** [comment]
Please use `Custom Purge URL` option from backend settings.
Add the forum index page(s) URL(s) in that, so if any topics are published/updated, then the forum index page will also get purged.
