### ISSUE TITLE
Allow custom path to cache storage option

### ISSUE THREAD

**Issue by wpbullet** [rtCamp/nginx-helper#127]
I'd like to request an option to choose the nginx cache path in case it is not the default of /var/run/nginx-cache similar to how https://github.com/tillkruss/Nginx-FastCGI-Cache does it.

It will allow greater flexibility for users who have different cache paths

**Comment by jynxy** [comment]
as in readme.

If your cache directory is different, you can override this in your wp-config.php by adding define('RT_WP_NGINX_HELPER_CACHE_PATH','/var/run/nginx-cache/');

**Comment by crdil** [comment]
I've defined the cache path like this.
define('RT_WP_NGINX_HELPER_CACHE_PATH','/var/run/nginx-cache/');
But when I purge the cache using GET or Delete local files, it wipes all directories in /run/nginx-cache/ .
How can I solve this?

I use a cache dir for each site I'm running.

**Comment by mrrobot47** [comment]
Closing this issue as it is stale.

>it wipes all directories in /run/nginx-cache/

This will happen when purge all is called from backend. Even in that case all directories inside folder `RT_WP_NGINX_HELPER_CACHE_PATH` (here `/var/run/nginx-cache/sitename`) will be wiped out, not all directories in `/var/run/nginx-cache`
