### ISSUE TITLE
Add Ability to Filter PurgeUrl

### ISSUE THREAD

**Issue by kingkool68** [rtCamp/nginx-helper#132]
Providing a hook to filter the URL before it is purged would be helpful.  Applying the filter here or on a new line after this one would work well https://github.com/rtCamp/nginx-helper/blob/c4dc90dbe248e883cb46f0a4f8a1108c3f26e627/redis-purger.php#L215

## Example Use Case

We run multiple servers behind a load balancer which terminates SSL connections. The request from the load balancer to the server happens unencrypted over port 80. We also use Redis caching and the cache keys get set as `http` via nginx's `$scheme` variable. On the WordPress side of things the `site_url` is set to `https` so the cache key that is attempted to be purged is like `httpsGET....` instead of `httpGET...`. The ability to adjust the URL before it is purged would be helpful in this instance.

It sounds like #124 could also benefit from a filter of the purgeURL.

**Comment by kingkool68** [comment]
I did manage to fix my issue by filtering `site_url` whenever it is being called from the Nginx Helper plugin like this:

```
add_filter( 'site_url', function( $url = '' ) {
    $backtrace = wp_debug_backtrace_summary();
    if ( stripos( $backtrace, 'rtCamp\WP\Nginx\Helper' ) ) {
        $url = str_replace( 'https://', 'http://', $url );
    }
    return $url;
});
```

**Comment by kingkool68** [comment]
Following up on this. I ran into some other issues where things like the homepage and archives weren't being purged when updating or adding a new post. My final solution is as follows:

```
/**
 * Change the site_url to http:// from https:// when being applied from the nginx helper
 * plugin. This is necessary for the cache purging to work due to other system issues.
 * @var string
 * @see https://github.com/rtCamp/nginx-helper/issues/132
 */
function sm_switch_to_http_for_cache_purging( $url = '' ) {
    $backtrace = wp_debug_backtrace_summary();
    if ( stripos( $backtrace, 'rtCamp\WP\Nginx\Helper' ) ) {
        $url = str_replace( 'https://', 'http://', $url );
    }
    return $url;
}
$filters = [
    'site_url',
    'home_url',
    'post_link',
    'term_link',
    'day_link',
    'month_link',
    'year_link',
    'post_type_archive_link',
    'author_link',
    'attachment_link',
];
foreach ( $filters as $filter ) {
    add_filter( $filter, 'sm_switch_to_http_for_cache_purging' );
}
```

A single filter would make this much easier but at least it is possible to use this as a work around.

**Comment by chandrapatel** [comment]
Hello @kingkool68 

I'm sorry for very late reply. We have introduced filter `rt_nginx_helper_purge_url` in version `2.1.0` which you can use to filter the URL before purge.

Please check https://github.com/rtCamp/nginx-helper/blob/master/admin/class-phpredis-purger.php#L106L113

Please let me know if it works and resolve your issue.

Thanks,
Chandra

**Comment by chandrapatel** [comment]
I'm closing this issue. Let me know if it does not work for you.
