### ISSUE TITLE
Worker process exits on signal 11 when trying to purge

### ISSUE THREAD

**Issue by chepurko** [rtCamp/nginx-helper#137]
Hi, I have NGINX compiled with the `--add-module=/tmp/naxsi/naxsi_src --add-module=/tmp/ngx_cache_purge` module options (placed first in the `./configure` order, if that matters). All of this stuff is running in Docker on a Kubernetes cluster with PHP FPM.

I'm on a single site setup using [this configuration](https://easyengine.io/wordpress-nginx/tutorials/single-site/fastcgi-cache-with-purging/). I have the `fastcgi_cache_path`, `fastcgi_cache_key`, `fastcgi_cache_use_stale`, and `fastcgi_ignore_headers` directives in the `http {}` context.

I can't get any of the cache files to purge using either the "Purge Entire Cache" button or the `PURGE/url` method. Neither does the automatic purging work (I'm verifying by watching the `/var/run/nginx-cache` directory).

When I try the `PURGE/url` method I get an NGINX error in the log - `[alert] 1#1: worker process 114 exited on signal 11`.

**Does the `/var/run/nginx-cache` directory have to be writable by the PHP FPM user? Currently that dir is with user/group `nginx` permissions and the FPM processes are user/group `www-data`.**

Additionally, the NGINX Helper logger is just returning `Purged Everything!`. Not sure what else I can check/try at this point...

NGINX version:
```bash
nginx version: nginx/1.12.0
built by gcc 6.3.0 20170415 (Debian 6.3.0-14) 
built with OpenSSL 1.1.0e  16 Feb 2017
TLS SNI support enabled
```

**Comment by chepurko** [comment]
Well I'm running NGINX with the same user as PHP FPM now and still no luck.

**Comment by mrrobot47** [comment]
Closing as stale. Please re-open if the issue still persists.
