### ISSUE TITLE
Purging does not happen when comment state changes from approved to unapproved

### ISSUE THREAD

**Issue by drscre** [rtCamp/nginx-helper#139]
Probably, due to a typo here:
https://github.com/rtCamp/nginx-helper/blob/master/purger.php#L54

Should it be 
`if ( $oldstatus == 'approved' ) {` 
instead of  
`if ( $oldstatus == 'approve' ) {` ?

**Comment by chandrapatel** [comment]
This has been fixed in version 2.0.0 so closing it.
