### ISSUE TITLE
Nginx Helper does not clear the cache

### ISSUE THREAD

**Issue by JamesMaxwel** [rtCamp/nginx-helper#149]
I’m using the latest version of the “Nginx Helper” plugin 1.9.11, together with easyengine and redis installed with the built-in eansyengine commands.
the cache works fine, but it is only cleaned with the “Redis Object Cache” plugin, the “Nginx Helper” plugin does not clear the cache the prefix settings are set in both plugins.
The Nginx and php logs do not report errors and the “Nginx Helper” plugin log reports that everything went well but the cache is not clean.
I am using Ubuntu 16.04 64x with easyengine, I have several sites created with the command “sudo ee site create example1.com –wp”, “sudo ee site create example2.com –wp”, …

**Comment by utan** [comment]
Hi,

It seems that its happening to me too..

Lastest nginx build with ngix purge module and ur wp plugin..
Is used in a buddypress install..

**Comment by JamesMaxwel** [comment]
in my case I was setting the prefix the wrong way, now it's working for me and all I had to do was just leave the default prefix

here is a config print, I use easyengine with redis
http://prntscr.com/l46bnh

**Comment by jcatello** [comment]
Not purging over here.

I've ensured prefix is correct.

**Comment by mrrobot47** [comment]
Closing this issue as it has been resolved.
