### ISSUE TITLE
Delete post/page cache on deletion of post/page

### ISSUE THREAD

**Issue by abhijitrakas** [rtCamp/nginx-helper#155]
When we trash  a post or page, the post/page still exists in cache and the user is served from cache. Need to delete cache on trash of post/page.

**Comment by rahulsprajapati** [comment]
Closing this PR in favor of https://github.com/rtCamp/nginx-helper/commit/da63e560b5ce063b58dbdc39307df08d74656c4d  commit in [v2-master](https://github.com/rtCamp/nginx-helper/tree/v2-master) branch.
