### ISSUE TITLE
Support custom fastcgi_cache_key setup ?

### ISSUE THREAD

**Issue by centminmod** [rtCamp/nginx-helper#161]
Would like to request that nginx-helper support setting up custom fastcgi_cache_key other than "$scheme$request_method$host$request_uri". 

I'd like to add caching for individual mobile user agents via an nginx mapped variable and define that instead

    fastcgi_cache_key "$scheme$request_method$host$request_uri$mobile"

**Comment by mrrobot47** [comment]
We have introduced multiple filters in [release 2.1.0](https://github.com/rtCamp/nginx-helper/tree/e7262a571f476347aebcbd6659b0497c41d006c0#210)

Please check the example in code comment given below, it is similar to your use case.
https://github.com/rtCamp/nginx-helper/blob/e7262a571f476347aebcbd6659b0497c41d006c0/admin/class-phpredis-purger.php#L124-L135

Closing this issue, fastcgi does not support wildcard or pattern based cache purging, if possible please move your cache from fastcgi to redis and use the above shared feature.
