### ISSUE TITLE
Trigger cache purge once a scheduled post is being published through wp_cron

### ISSUE THREAD

**Issue by ggloveswp** [rtCamp/nginx-helper#164]
I am aware of the CLI command: **wp nginx-helper purge-all** that can be used to purge the entire cache and also of the options that nginx helper plugin has.

I was wondering if there is any way to trigger the plugin's functionality once a scheduled post is being published, for this specific post, since plugins' options are all about posting by pressing the publish button/comment edits etc, but not scheduling scenarios of WordPress.

Synopsis: Adding a new options at the UI, under **Purge Post/Page/Custom Post Type** section:
**- when a scheduled post changes status to published**

**Comment by Endda** [comment]
bump, any progress about this? I'm having trouble with scheduled products from Woocommerce not purging the Redis cache

**Comment by arafatkn** [comment]
Thanks, @ggloveswp, @Endda  & @ozgurkazancci for raising the issue.

I have tried to reproduce the scenario. On my end, `nginx-helper` plugin is purging the cache of the scheduled post while publishing through wp_cron. It works perfectly not only for posts but also for all custom post types.
If you are still facing the issue, then please enable `logging` (_Settings > Nginx Helper > Debug Options_) and share the logs here.

**Comment by gagan0123** [comment]
@ggloveswp, @Endda & @ozgurkazancci

Can anyone provide an update on this?

I tested things out with scheduled posts and yet the plugin never failed to purge those posts.

Here are the specific lines of code that ensures the plugin works even for scheduled posts, that is hooked on `transition_post_status` action
https://github.com/rtCamp/nginx-helper/blob/1767a84b2f7687b07912307a37c073a6e001a09f/admin/class-nginx-helper-admin.php#L590-L614

**Comment by ggloveswp** [comment]
> @ggloveswp, @Endda & @ozgurkazancci
> 
> Can anyone provide an update on this?
> 
> I tested things out with scheduled posts and yet the plugin never failed to purge those posts.
> 
> Here are the specific lines of code that ensures the plugin works even for scheduled posts, that is hooked on `transition_post_status` action
> 
> https://github.com/rtCamp/nginx-helper/blob/1767a84b2f7687b07912307a37c073a6e001a09f/admin/class-nginx-helper-admin.php#L590-L614

Last version seems to be working fine for me.

**Comment by gagan0123** [comment]
Thanks @ggloveswp for confirming 😃
