### ISSUE TITLE
Widgets Not Saving - Call to undefined function wp_parse_url()

### ISSUE THREAD

**Issue by tjhawk** [rtCamp/nginx-helper#166]
Updated plugin to version 2.0.1. Now we are seeing a 500 error in the browser console when saving widgets and changes are not saved.

Looked in the server logs and see the following error.

PHP message: PHP Fatal error:  Call to undefined function wp_parse_url() in /var/www/assets/plugins/nginx-helper/admin/class-fastcgi-purger.php on line 33

Please advise on a fix ASAP! Our production sites are affected.

**Comment by tjhawk** [comment]
I temporarily changed line 33 and 94 by removing the call to the function.

Line 33: $parse = $url;

Line 94: $parse = site_url();

Not sure of side effects but we are able to save widgets now but will wait for a permanent fix.

**Comment by chandrapatel** [comment]
Hi @tjhawk 

Apologies for the issue. 

Can you please let me know which WordPress version you're using?

**Comment by chandrapatel** [comment]
No updates on this so closing it.
