### ISSUE TITLE
Nginx maps fail in multi network

### ISSUE THREAD

**Issue by AmibeWebsites** [rtCamp/nginx-helper#198]
While in one network, map.conf is generated based on sites in that network - sites from other networks are not included. When you switch to another network in the same multi-site install, map.conf is generated based on sites in **that** network, overwriting the one from the first network.

Before I do a pull request and start changing code there are two ways to solve this that warrant some discussion first.

**OPTION 1:**

List ALL sites across ALL networks regardless of the current network, saving to one map.conf file.

Pros:

1. One map.conf file so no changes required in Nginx configuration files that include the mappings.

Cons:

1. It's not ideal to list all sites regardless of network as each network might have different administrators. This could be circumvented if what's shown on the screen is only for the network but what's saved is for all.
2. Possible performance implications for installations with thousands of websites across hundreds of networks.

**OPTION 2:**

Create a separate map_<network-id>.conf per network.

Pros:

1. Clean separation between networks.
2. No performance overhead.

Cons:

1. Each new network would generate a new map file that needs to be included in the Nginx config.
2. Changes to the naming of map.conf would impact all existing implementations!

Both these cons could be circumvented by also generating a map.conf that includes all the individual map_<network-id>.conf files - this would also allow for this change to be implemented without affecting any existing installations.

Having now typed this out my feeling is that Option 2 is the preferable one.

**Comment by chandrapatel** [comment]
Closing this issue because we haven't planned supporting multi-network.
