### ISSUE TITLE
Add support for device type in nginx helper

### ISSUE THREAD

**Issue by pradeep910** [rtCamp/nginx-helper#202]
`device_type` variable was added in some sites. 
For this, changes were made in nginx-helper plugin itself for the site instead of using filter / action hooks. 

- [x] Add a filter to nginx-helper plugin.

- [x] Use filter to add enable device type.

**Comment by kirtangajjar** [comment]
@pradeep910 @chandrapatel Please do comment on https://github.com/rtCamp/nginx-helper/issues/202 once this is done.

**Comment by chandrapatel** [comment]
@pradeep910 Since actions & filters released in `2.1.0` so I'm closing this issue.
