### ISSUE TITLE
Update map.conf automatically?

### ISSUE THREAD

**Issue by jockebq** [rtCamp/nginx-helper#216]
Just got your plugin, and it does its job well.
But I am using a plugin called WP Ultimo, which creates a Multisite network. And when a user adds or removes a site the map.conf doesn't get automatically updated.
I have to manually go into the settings and save changes for it to update.

Is it possible to automatically update on a new site or removed site?

**Comment by chandrapatel** [comment]
Hello @jockebq 

`map.conf` file will update automatically when new site add from `Network Admin -> Sites -> New Site`. 

We haven't tested our plugin with WP Ultimo plugin.

**Comment by chandrapatel** [comment]
I'm closing this issue since we are not planning to support WP Ultimo.
