### ISSUE TITLE
Logging bug

### ISSUE THREAD

**Issue by rahul286** [rtCamp/nginx-helper#22]
From mjbrown:

> It seems that for logging to be enabled, the nginx-helper plugin requires that the nginx.log file exists and does not create it; hence the error message. There does not seem to be a filesystem permission problem per se.

Ref: http://rtcamp.com/support/topic/no-entries-in-map-conf/#post-21958

**Comment by robrecord** [comment]
Still not fixed?

**Comment by chandrapatel** [comment]
Seems like this issue has been fixed so closing this.
