### ISSUE TITLE
Compatibility and conflict issue with AMP plugins and user front end Pro Plugin

### ISSUE THREAD

**Issue by techzotezo** [rtCamp/nginx-helper#233]
Hi,
We are facing plugin compatibility issues with AMP for wp and wp user frontend plugins.
when your plugin has enabled then the following issues are happening 
1) All desktop pages are becoming AMP pages sometimes
2) Sites become slow
3) wp user frontend plugins was slow when your plugins are enabled.

What is the reason of this? How to rectify from this?
Thanks,

**Comment by Ruzgfpegk** [comment]
I think this has nothing to do with the plugin, but instead with how the nginx cache has been set up (as I suppose you're using its cache).

When using AMP, the cache key setting in nginx should take into account the device used.

Sadly using the exact [set of rules used by AMPforWP](https://github.com/ahmedkaludi/accelerated-mobile-pages/blob/master/includes/vendor/Mobile_Detect.php) for a perfect 1:1 match seem hardly feasible to me, but you can try to get close to it through a regexp like :

```
set $device "pc";

if ($http_user_agent ~* "Android .+ Mobile|\(iPhone|\(iPod|IEMobile|Android; Mobile; .+Firefox|Windows Phone") {
	set $device "smart";
}

fastcgi_cache_key    "$device:$request_method:$scheme://$host$request_uri";
```

**Comment by mrrobot47** [comment]
Closing as not related to the plugin.
