### ISSUE TITLE
Memcached support

### ISSUE THREAD

**Issue by bogdanpetrea** [rtCamp/nginx-helper#244]
Hi, I would like to add support for Memcached to this plugin.

I've tested a bit to see how such an implementation would look like, and I think it's a good attempt. But Memcached is way more simple than Redis and it lacks support for wildcard keys, and that poses a certain cache invalidation problem, which I'd like to discuss here before submitting a PR.

#### Initial implementation
Initially I implemented the wildcard invalidation by using [Memcached::getAllKeys](https://www.php.net/manual/en/memcached.getallkeys.php), but that function is not guaranteed to return all the actual keys, it might be slow for many keys and it's generally recommended only for debug purposes.
Another downside to this solution is that if you are using [mcrouter](https://github.com/facebook/mcrouter) (which is part of my usecase at least), it will not work as there is no `getAllKeys` implementation there. But for usecases involving relatively small caches, with no mcrouter, it might do the trick...

#### Second implementation
In order to avoid the above mentioned downsides, I've read about how multi-key cache invalidation should be done when using Memcached, and implicit invalidation was a solution I found: You basically version your cache keys (with say a number: `nginx-cache:12345:httpsGETxyz`) and change the version to invalidate the keys.

So I store a version that doesn't expire in Memcached, I retrieve it (and create it if it's missing) from Memcached in my Nginx conf via Lua, I use it to build the cache key and from there it's basically the same. [Here's an example](https://github.com/presslabs/stack-runtimes/pull/15/files#diff-3dfab93f3c9a20f36393b3548026f73d) I've put up. The cache invalidation in nginx-helper would be just deleting the version key from Memcached.

~~The downside to this is that it's restricted to one site per Memcached instance.~~ I've put a field for customizing the versioned cache key, so the issue is solvable, at least from the nginx conf.
And of course you miss out on the wildcard invalidation, but you can't have it all with Memcached. There's always Redis for that.

#### PR implementation
So what do you think my course of action should be here? I could keep both implementations and have a toggle for implicit invalidation in the plugin's Memcached settings, for users to choose... I did just that: https://github.com/rtCamp/nginx-helper/pull/245

**Comment by chandrapatel** [comment]
Hi @bogdanpetrea 

Thanks for opening the issue and sending the pull request. We will check and discuss internally to add support for Memcached.

**Comment by rahul286** [comment]
@bogdanpetrea I am concerned about performance of wildcard purge.

In Redis, we use integrated Lua script to purge matching pages. It always takes one call from PHP process to Redis server no matter how many matching entries we need to delete from the cache.

Here is the code ➞ https://github.com/rtCamp/nginx-helper/blob/c3632f582662de058c8a53a613951a58d04c4101/admin/class-predis-purger.php#L250-L258

When I tested last time it deleted 10000+ matching entries very quickly. I can't recall exact time but it was always than a second.

May I know if you have tested wildcard cache purge for large number of matching keys?

cc: @mrrobot47

**Comment by bogdanpetrea** [comment]
Hey @rahul286 , I can see why that would be a concern. I haven't tested for a large number of matching keys, but I would assume it's slow. There's not much that can be done to improve performance in that case, except for using Redis instead of Memcached.
Do you think only the versioned key implementation should be kept?

**Comment by rahul286** [comment]
@bogdanpetrea May I know why you are not using Redis in your application?

**Comment by bogdanpetrea** [comment]
We're already using Memcached for Wordpress object caching, scaled horizontally with McRouter. So we decided it's easier to reuse this setup, rather than go with the overhead of using Redis as well. Also in some benchmarks, Memcached comes out as a faster solution, but then as with all benchmarks this doesn't mean it's the case for everyone:
https://blog.kernl.us/2020/02/should-i-use-memcached-or-redis-for-wordpress-caching/

We do intend to support Redis as well in our implementation, so ultimately it will be a user choice.

**Comment by mrrobot47** [comment]
@bogdanpetrea currently we do not plan to support and maintain Memcached caching method in nginx-helper. Please feel free to add this feature to a fork.

Thank you, stay safe :slightly_smiling_face:

**Comment by bogdanpetrea** [comment]
Alright. Thanks and take care!
