### ISSUE TITLE
Undefined index: path

### ISSUE THREAD

**Issue by ArtDubrovsky** [rtCamp/nginx-helper#251]
Good day,
after turning wp_debug on I've found some of 

`PHP Notice:  Undefined index: path in /htdocs/wp-content/plugins/nginx-helper/admin/class-purger.php on line 390`

at debug.log

I've not realised yet what is a scenario invokes this notice, but changed the original string to 

`$hash = md5( $url_data['scheme'] . 'GET' . $url_data['host'] . wp_parse_url( $url, PHP_URL_PATH ) );`

**Comment by glagonikas** [comment]
This seems to be related to #190 

We have the same issue and as the error states, it's happening here https://github.com/rtCamp/nginx-helper/blob/2.2.2/admin/class-purger.php#L390
