### ISSUE TITLE
functionality for caching ( and flashing ) according to a combination of cookies?

### ISSUE THREAD

**Issue by eddr** [rtCamp/nginx-helper#282]
Hi

Can this plugin support such functionality?
Caching pages also according to a combination of cookies (name + value)

An example from a live site:
cookie 1 : country
cookie 2 : currency

can be : es_usd or es_eur or ro_gbp

Thanks!

**Comment by gagan0123** [comment]
@eddr 

Handling how NGINX caches the requests can be done via modifying the NGINX config, though that is out of the scope of plugin as this plugin does not modify any NGINX configs.

Here's some reference that can help you out configuring NGINX as per your requirement:
https://www.nginx.com/blog/nginx-caching-guide/

Closing the issue as this can't be achieved via the plugin.
