### ISSUE TITLE
On settings page, Inside logging options the log path is not visible 

### ISSUE THREAD

**Issue by pavanpatil1** [rtCamp/nginx-helper#284]
log path is not visible on the settings page. 

![image](https://user-images.githubusercontent.com/44057535/197190269-3175aea8-73dc-4fc8-939e-65a064e336e3.png)

**Comment by danish17** [comment]
Not able to reproduce on:
```
PHP: 8.0.26 (fpm-fcgi)
WordPress: 6.1.1, 5.9
```
![image](https://user-images.githubusercontent.com/24435748/214892895-3b1b9bf1-41f2-447a-8f9d-a740d9f98c17.png)

**Comment by pavanpatil1** [comment]
Verified the issue with the PHP8 and WP 6.1.1, Working fine. Hence closing this issue. 


![image](https://user-images.githubusercontent.com/44057535/215118187-a08501c7-e6ef-46b6-a267-08b1728e537e.png)
