### ISSUE TITLE
Cloudflare with Nginx Helper: "cf-edge-cache response header is missing! "

### ISSUE THREAD

**Issue by bozzmedia** [rtCamp/nginx-helper#286]
Using Cloudflare + nginx helper, the APO mechanism in Cloudflare complains that 

"cf-edge-cache response header is missing! Please clear any server cache used via other plugins."

When I clear nginx cache the issue goes away. 

Is there a certain configuration step I need to deal with to work with both Cloudflare + nginx?

Thanks!

**Comment by gagan0123** [comment]
@bozzmedia 

Modifying the nginx config itself is out of the scope of this plugin. The plugin only helps when nginx is correctly configured to handle purge requests. You'll need to modify the nginx config to add new headers.
Here's some reference on how to add it in nginx config: https://nginx.org/en/docs/http/ngx_http_headers_module.html#add_header
