### ISSUE TITLE
PHP 8.1 compatibility

### ISSUE THREAD

**Issue by dhsathiya** [rtCamp/nginx-helper#291]
Getting PHP Deprecated notics when switching my php version from 7.4 to 8.1
Please fix to make your plugin perfectly compatible with php 8.1:
```
[19-Aug-2022 19:02:23 UTC] PHP Deprecated:  Constant FILTER_SANITIZE_STRING is deprecated in /wp-content/plugins/nginx-helper/admin/class-nginx-helper-admin.php on line 676
[19-Aug-2022 19:02:23 UTC] PHP Deprecated:  Constant FILTER_SANITIZE_STRING is deprecated in /wp-content/plugins/nginx-helper/admin/class-nginx-helper-admin.php on line 681
```
Ref - https://wordpress.org/support/topic/php-8-1-compatibility-7/

**Comment by danish17** [comment]
@Souptik2001, did you make any fixes?

**Comment by Souptik2001** [comment]
@danish17 Yes the fixes are done. We are in the testing phase now.

**Comment by aviral-mittal** [comment]
@Souptik2001 Can you please point us to the PR in which this fix has been made.

**Comment by Souptik2001** [comment]
@aviral-mittal I have not yet raised the PR as all the tests are not yet complete.
Just FYI here is the branch with the changes - https://github.com/Souptik2001/nginx-helper/tree/fix/GH-291

**Comment by gagan0123** [comment]
@Souptik2001 Any estimates on when the tests will be completed?

**Comment by Souptik2001** [comment]
@gagan0123 It should be done by tomorrow. Starting with multi-site testing now.

**Comment by pgnd** [comment]
@Souptik2001 @gagan0123 

what are current plans for merging this fix, and pushing a release ?

**Comment by dhsathiya** [comment]
We have provided PHP8.1 compatibility with the [latest release](https://github.com/rtCamp/nginx-helper/releases/tag/2.2.3).
Closing the issue in favour of the same.
