### ISSUE TITLE
Timestamp injects in AJAX repsonse

### ISSUE THREAD

**Issue by rahul286** [rtCamp/nginx-helper#30]
@yapapaya please check - http://rtcamp.com/support/topic/activating-nginx-helper-breaks-gs-star-rating-plugin/

Functionality which depends on AJAX response breaks because HTML timestamps gets inserted in JSON packets!

Also, timestamp option should be OFF by default. I guess its already OFF by default.

**Comment by chandrapatel** [comment]
This has been fixed so closing it.
