### ISSUE TITLE
Vulnerability issue

### ISSUE THREAD

**Issue by JoeyLLK** [rtCamp/nginx-helper#317]
Hello
Thanks for a great plugin.
Our website security software has today identified a vulnerability with Ngnix helper. We are still looking into this, but is there an update planned?
Luke

**Comment by JoeyLLK** [comment]
It has been identified as a "Sensitive Data Exposure vulnerability in WordPress Nginx Helper Plugin". Not sure of the details at this stage

**Comment by gagan0123** [comment]
This was already reported by another user here:

https://github.com/rtCamp/nginx-helper/issues/315

Marking this as duplicate, providing more details in the previously reported GitHub issue, to keep all information regarding this in one place.
