### ISSUE TITLE
Call to undefined function rtCamp\WP\Nginx\unlinkRecursive()

### ISSUE THREAD

**Issue by bdtech** [rtCamp/nginx-helper#36]
I get this after performing your latest update today in Wordpress then clicking Purge which came up with a quick 500 error.

PHP Fatal error:  Call to undefined function rtCamp\WP\Nginx\unlinkRecursive() in /srv/www/wpress/wp-content/plugins/nginx-helper/purger.php on line 693"

**Comment by chandrapatel** [comment]
We have refactored the plugin codebase in version 2.0.0 so this issue is no longer exist. I'm closing this issue.
