### ISSUE TITLE
Unlink Issue - Latest WP Plugin

### ISSUE THREAD

**Issue by bdtech** [rtCamp/nginx-helper#37]
2013/04/24 20:48:42 [error] 2609#0: *18 FastCGI sent in stderr: "/var/run/nginx-cache/6/81): Is a directory in /srv/www/xyz.com/wp$

PHP message: PHP Warning:  unlink(/var/run/nginx-cache/0/6e): Is a directory in /srv/www/xyz.com/wpress/wp-content/plugins/nginx-h$
$ginx-helper/purger.php on line 692

Error is repeated several times for various cache files

**Comment by chandrapatel** [comment]
This issue is no longer exists in the plugin so closing it.
