### ISSUE TITLE
Custom post type doesn't fire purge action

### ISSUE THREAD

**Issue by szaqal83** [rtCamp/nginx-helper#39]
When I add or modify a custom post type purge isn't fired. After small search I've found that line 52 in nginx-helper.php prefents adding "publish_..." action. There is a check of "rt_wp_custom_post_types" but I haven't found any place there this option is being set and foreach tries to iterate over $_rt_custom_post_types but this isn't set. I've fixed it by:

``` php
$post_types = get_post_types( $args );
            if ( isset( $post_types ) && ! empty( $post_types ) ) {
                // if ( $this->options[ 'rt_wp_custom_post_types' ] == true ) {
                    foreach ( $post_types as $post_type ) {
                        add_action( 'publish_' . trim( $post_type ), array( &$rt_wp_nginx_purger, 'purgePost' ), 200, 1 );
                    }
                // }
            }
```

**Comment by chandrapatel** [comment]
This issue has been fixed in version 1.9.1 so I'm closing it.
