### ISSUE TITLE
Post switched to draft isn't purged when using custom permalink

### ISSUE THREAD

**Issue by szaqal83** [rtCamp/nginx-helper#42]
I've a cron task which turns old posts to drafts after task is done post still presists in fastcgi cache because when purge is being fired get_permalink() returns basic link (...?p=555) and post isn't being purged. I've found a function which could help:

``` php
function get_draft_permalink( $post_id ) {
            require_once ABSPATH . '/wp-admin/includes/post.php';

            list( $permalink, $postname ) = get_sample_permalink( $post_id );

            return str_replace( '%postname%', $postname, $permalink );
        }
```

there could be a check of post_status when purge_by_option() to fix get_permalink() result.

**Comment by chandrapatel** [comment]
This issue has been fixed in version 2.0.2 so I'm closing it.
