### ISSUE TITLE
Clear multiple Schemes

### ISSUE THREAD

**Issue by JCBauza** [rtCamp/nginx-helper#54]
Currently it only purges the cache for http (or https), would be nice if it could send the request to clear both. 
Also, at some point I get lots of requests for purging that take a hit on the server trying to call out all those pages... I wonder if there could be a faster method rather than doing the standard POST or keep in cache a list of the existing cache and only clear the desired ones.

**Comment by xavivars** [comment]
@rahul286 the original issue still exists in Redis: when you need to purge more than one schema (or a different one from the one define in the site_url). That happens, for example, if your WordPress is being served behind a proxy:

* Nginx A deals with SSL
* Nginx B listens to port 80, has redis cache and serves WordPress (having HTTPS as a schema for the site url).

It would be awesome if it existed a filter to to change the schema. I can work on implementing one, but would it be accepted as a pull request? I've seen there exist some pull requests with interesting features contributed by the community pending for months in the repo...

**Comment by mrrobot47** [comment]
@xavivars we have introduced multiple filters in [release 2.1.0](https://github.com/rtCamp/nginx-helper/tree/e7262a571f476347aebcbd6659b0497c41d006c0#210)

Please check the following filter by which you can change the schema in URL.
https://github.com/rtCamp/nginx-helper/blob/e7262a571f476347aebcbd6659b0497c41d006c0/admin/class-phpredis-purger.php#L106-L113

As of now we are planning on supporting the purging of multiple schemas. So closing the issue.
