### ISSUE TITLE
purge does not work when using PHP-FPM with another user

### ISSUE THREAD

**Issue by hostingnuggets** [rtCamp/nginx-helper#63]
I am using nginx helper 1.8.1 along with fastcgi caching and I noticed that the purging does not work. The problem here is that I have one PHP-FPM pool per website using another user account each. My nginx runs as www-data and so the files created by FastCGI caching also belongs to www-data. This means that the nginx helper can not delete (unlink) the cache file because that PHP-FPM runs as another user. Do you have any work around for that or any solution?

Why not always use the /purge URL instead of unlinking files?

Here would be the PHP-FPM error message just in case:

2014/06/16 12:42:23 [error] 28902#0: *41796 FastCGI sent in stderr: "PHP message: PHP Warning:  opendir(/var/run/nginx-cache/mywebsite.com/): failed to open dir: Permission denied in /var/www/mywebsite.com/htdocs/wp-content/plugins/nginx-helper/purger.php on line 686" while reading response header from upstream, client: XX.XX.XX.XX, server: www.mywebsite.com, request: "GET /wp-admin/post.php?post=482&action=edit&message=1&nginx_helper_action=purge&nginx_helper_urls=all&_wpnonce=a382bcef22 HTTP/1.1", upstream: "fastcgi://unix:/var/lib/nginx/fastcgi/mywebsite.com.sock:", host: "www.mywebsite.com", referrer: "http://www.mywebsite.com/wp-admin/post.php?post=482&action=edit&message=1"

**Comment by danimalweb** [comment]
I know it's been a few years, but any updates on this? Is there a better way?

**Comment by Xlebomnekormi** [comment]
Hello everyone!
Any update on this matter? 
Thanks

**Comment by filipecsweb** [comment]
Did anyone find a solution for this?

**Comment by mrrobot47** [comment]
Closing this issue is stale and we are not planning to support of PHP-FPM with another user.

**Comment by webaware** [comment]
I hit this problem, and solved it by using one of the scripting languages supported by nginx -- either Lua or Perl will do.

https://snippets.webaware.com.au/snippets/purging-nginx-cache-users-differ/

**Comment by josbroers** [comment]
I've figured out how both Nginx and PHP should have the necessary access to the cache directory through the common group. Assuming your PHP-FPM process is running as example-user, follow these steps:

**1. Create a Common Group:**
Create a new group, let's call it `example-user-cache`:

```bash
sudo groupadd example-user-cache
```

**2. Add Users to the Group:**
Add both the `www-data` (Nginx) and `example-user` (PHP) users to the `example-user-cache` group:

```bash
sudo usermod -aG example-user-cache www-data
sudo usermod -aG example-user-cache example-user
```

This command appends the specified group (`example-user-cache`) to the list of supplementary groups for each user.

**3. Set Group Ownership:**
Change the group ownership of the cache directory to the newly created group:

```bash
sudo chown -R www-data:example-user-cache /var/run/nginx-cache/mywebsite.com
```

**4. Set Group Permissions:**
Set the group permissions on the cache directory:

```bash
sudo chmod -R 770 /var/run/nginx-cache/mywebsite.com
```

This allows both the Nginx user and the PHP user in the `example-user-cache` group full access.

**5. After making these changes, restart both Nginx and PHP-FPM:**

```bash
sudo systemctl restart nginx && sudo systemctl restart php*
```
