### ISSUE TITLE
define( 'DISALLOW_FILE_MODS', true ); disables admin options page

### ISSUE THREAD

**Issue by ghost** [rtCamp/nginx-helper#66]
`define( 'DISALLOW_FILE_MODS', true );` disables `update_plugins, delete_plugins, install_plugins, update_themes, delete_themes, install_themes, update_core`

`add_submenu_page` should use something like `manage_options` instead of `install_plugins`.

**Comment by chandrapatel** [comment]
That PR has been merged and the issue fixed so closing it.
