### ISSUE TITLE
Adding ?get_feeds=1 to any URL -> rtCamp link farm?

### ISSUE THREAD

**Issue by d--j** [rtCamp/nginx-helper#68]
Shouldn't https://github.com/rtCamp/nginx-helper/blob/master/nginx-helper.php#L385 be

``` php
add_action('admin_init', 'fetch_feeds');
```

?

Otherwise adding `get_feeds=1` to any WordPress URL (even frontend URLs!) would result in showing links to the five last rtCamp blog posts.
E.g. visit https://rtcamp.com/blog/?get_feeds=1 or any other WordPress site that uses this plugin to see this.

Also changing `get_feeds` to something less generic would probably be beneficial, to reduce the probability of other plugins using the same parameter name.

**Comment by chandrapatel** [comment]
Hi @d--j 

Thanks for this issue. I've refactored code and used WP Ajax to display the latest news. The following PR will merge in next release.

PR -- https://github.com/rtCamp/nginx-helper/pull/147/files
