### ISSUE TITLE
multi-page comment purging

### ISSUE THREAD

**Issue by pjv** [rtCamp/nginx-helper#71]
I've just discovered an issue related to purging posts and pages on approval/unapproval of new comments when the discussion setting in wordpress for "Break comments into pages with..." is set.

If wordpress is set to paginate for comments, then request_uri's get sections appended to them like `comment-page-1/`. So you might have a blog post with a baseuri that looks like `http://myblog.com/this-is-a-post/`, and then if there are several pages of comments wordpress will also generate, and nginx will also cache: `http://myblog.com/this-is-a-post/comment-page-1/, http://myblog.com/this-is-a-post/comment-page-2/, etc.`

Then when a comment is approved or unapproved and nginx-helper goes to purge the post or page that was commented on, it only knows the base uri and it only purges the base uri. All the potential pagination pages like `baseuri/comment-page-1/, baseuri/comment-page-2/, etc` do not get purged.

I thought I would just code up a quick fix for this and send a pull request, but when I started thinking about how to deal with it, I got stuck. Would the only way to deal with it be looking at the comments per page setting and using the core paginator to determine how many pages to purge and then generating those URI's dynamically and passing them to the purge location? That seems like a lot of overhead.

In the [nginx documentation](http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_cache), I found a tantalizing section that says this:

> If the cache key of a purge request ends with an asterisk (“*”), all cache entries matching the wildcard key will be removed from the cache.

...so the first thing I tried was going into my nginx conf and sticking an asterisk on the end of the cache key for the /purge/ location like so:

```
    location ~ /purge(/.*) {
        fastcgi_cache_purge WORDPRESS "$scheme$request_method$host$1*";
    }
```

but it didn't give me the result that I was hoping for.

Anyone have any good ideas?

**Comment by mrrobot47** [comment]
We have introduced multiple filters in [release 2.1.0](https://github.com/rtCamp/nginx-helper/tree/e7262a571f476347aebcbd6659b0497c41d006c0#210)

You can try the below one and add `*` in it for purging wildcard cache keys for that URL as shown in the example in code comment.
https://github.com/rtCamp/nginx-helper/blob/e7262a571f476347aebcbd6659b0497c41d006c0/admin/class-phpredis-purger.php#L124-L135

Closing this issue, in case you are not able to achive wildcard purging with this, feel free to re-open this.
