### ISSUE TITLE
WP-CLI Integration

### ISSUE THREAD

**Issue by michaelryanmcneill** [rtCamp/nginx-helper#75]
I'd really like to see WP-CLI integration in this plugin. We use this in a distributed environment, and being able to purge the cache from the command line would be a huge improvement. Right now we manually clear the cache using `rm -rf /var/run/nginx-cache/*`, but it would be great to execute the command via WP-CLI.

**Comment by rahul286** [comment]
@michaelryanmcneill can you please give some useful links and examples? We might be able to do that integration easily with some inputs.

By the way, we use this plugin mostly with https://github.com/rtCamp/easyengine and easyengine has command to clean cache `ee clean`. You can use this command if you are also using easyenigne on server - http://docs.rtcamp.com/easyengine/commands/clean/

**Comment by desaiuditd** [comment]
This would be a bit tricky!

`/var/run/nginx-cahe` falls under `root` user. Our PHP processes run under `www-data` & `WP_CLI` prefers that any command should run under the user that your WordPress install exists under. Though we could bypass it with `--allow-root` flag of `WP_CLI`

Have sent a PR for a kickstarter `purge-all` command. Other commands can be added the same way.

**Comment by rahul286** [comment]
Thanks @desaiuditd 

I guess permission won't be an issue as long as `/var/run/nginx-cache` is owned by `www-data`. This is case with EasyEngine as well as our manual tutorials - https://rtcamp.com/wordpress-nginx/tutorials/

@michaelryanmcneill  I hope this fixes your issue.

**Comment by michaelryanmcneill** [comment]
@rahul286 thanks so much for the ee clean command. I didn't know it existed and I'll check it out for the environments that I use EasyEngine on. Unfortunately some of my environments (and this one specifically) are not using EasyEngine, so I needed another way to do it. 

@desaiuditd You're the best, thanks for kicking this off. If I find any sort of other implementation I think would be helpful, I'll let you know!
