### ISSUE TITLE
Needs an update script for 1.8.8

### ISSUE THREAD

**Issue by claudiosmweb** [rtCamp/nginx-helper#79]
I just updated and the options show:

![screenshot from 2015-04-21 11 38 05](https://cloud.githubusercontent.com/assets/1264099/7254679/00c26ed0-e81b-11e4-8beb-a079df29b588.png)

**Comment by rahul286** [comment]
Looks like this is missed in #78 

@bcole808 can you please have a look?

**Comment by rahul286** [comment]
@claudiosmweb 

Please update to 1.8.9

I hope it fixes this.

**Comment by claudiosmweb** [comment]
Thanks :)
