### ISSUE TITLE
post / home page cache and multisite setup

### ISSUE THREAD

**Issue by anantshri** [rtCamp/nginx-helper#83]
One of my setup has blog admin on a seperate domain and the resulted blog is displayed on a different domain. I suppose nginx-helper doesn't handles this case very well coz i need to invalidate the cache manually to get the page to reflect post updates and home page update.

can you help in trouble shooting this.

Edit : i suppose this might be a duplicate on #44 but still need support on fixing this.

**Comment by mrrobot47** [comment]
Nginx-helper builds cache key for purging using [home url](https://developer.wordpress.org/reference/functions/home_url/), if your Nginx is using a separate domain in building the cache key, then this issue can arise.

Please update the cache key generation on Nginx side and keep it in sync with the site's [home url](https://developer.wordpress.org/reference/functions/home_url/). Then purging should work as expected.

Closing this issue, in case you are still facing this after updating your Nginx config, please re-open the issue and share your frontend domain as well as nginx config.

**Comment by anantshri** [comment]
I hope you do realize the multisite setup would mostly never have that config and hence effectively you have said that you can't fix the issue.
