### ISSUE TITLE
Header image in README.md

### ISSUE THREAD

**Issue by michaelbeil** [rtCamp/nginx-helper#86]
`![alt text](https://plugins.svn.wordpress.org/nginx-helper//assets/banner-772x250.png)` doesn't show up because the MIME type has not been set correctly for the .org repo. 

Also, there's a double `//` before assets. 

#85 fixes the double `//`, but the MIME type needs to be fixed. 

Reference: https://make.wordpress.org/plugins/2014/03/20/plugin-screenshots-downloading.

```svn propset svn:mime-type image/png screenshot-1.png```

Otherwise it could just be referenced from elsewhere.

**Comment by rahul286** [comment]
We have removed header image from github readme.md

Thanks for workaround though. Will help us somewhere else.

If you find any other issues, please report them.
