### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by michaelbeil** [rtCamp/nginx-helper#87]
You may want to disconnect Travis CI as you don't have a .travis.yml file ... 

https://travis-ci.org/rtCamp/nginx-helper/builds/65115443

**Comment by rahul286** [comment]
@michaelbeil we added support for https://github.com/rtCamp/nginx-helper/blob/master/.travis.yml

Hope nginx-helper will be more stable and better now. :-)

**Comment by michaelbeil** [comment]
That's great news. 👍🏻
