### ISSUE TITLE
Purge Cache link in admin bar issues

### ISSUE THREAD

**Issue by rawcreative** [rtCamp/nginx-helper#89]
The Purge cache in the admin bar currently does not work, as it is outputting the url with the & on the nonce escaped:
`/wp-admin/edit.php#038;action=edit&message=1&nginx_helper_action=purge&nginx_helper_urls=all`

This is because in admin.php, the ```$purge_url``` variable is ran through esc_url, before passing it to wp_nonce_url, which also escapes html.
https://github.com/rtCamp/nginx-helper/blob/master/admin/admin.php#L121-L122

**Comment by rahul286** [comment]
I hope recent release fixes this.
We have verified it with redis-cache.
