### ISSUE TITLE
PHP Notice

### ISSUE THREAD

**Issue by zanematthew** [rtCamp/nginx-helper#90]
On the initial loading of the settings there a PHP notice for an undefined index when "Enable Logging" is not set. However if you set-it, save the settings, the notice goes away, then you can uncheck the box again, and the notice is no longer present.

It seems the [sane options](https://make.wordpress.org/themes/2014/07/09/using-sane-defaults-in-themes/) approach as required in theme options/settings is not being used.

**Comment by rahul286** [comment]
@zanematthew I think this is fixed in - https://github.com/rtCamp/nginx-helper/pull/99

Can you please confirm?

**Comment by zanematthew** [comment]
Looking into this...

**Comment by zanematthew** [comment]
@rahul286 Yep this issue no longer happens. 

Although I did notice that the default options are written to the database during plugin install, rather than using the sane option approach mentioned in the link above.

> That means that Themes must not write default setting values to the database 

Honestly this probably isn't a big deal, btw great plugin!

**Comment by rahul286** [comment]
> That means that Themes must not write default setting values to the database

I wholeheartedly agree with that. The current codebase is developed by 20+ people so it's slightly messy.

We will try our best to follow above and other coding practices during major refactoring.

Thanks.

**Comment by zanematthew** [comment]
I could imagine.
