### ISSUE TITLE
option to purge cache on multiple servers

### ISSUE THREAD

**Issue by harshadyeola** [rtCamp/nginx-helper#93]
Situation

`Traffic => Proxy Server (Redis Cache) => Main Server (Redis Cache) -> fpm`

`Purge (Nginx Helper) => Main Server(Redis cache) (does not purge on proxy server)`

Idea is to provide an option to add multiple server list having redis cache for site. so that they can be purged if main server is purged

`Purge (Nginx Helper) => Main Server + Proxy Server (Redis Cache)`

**Comment by mrrobot47** [comment]
It is better to keep page cache at any one place.
Closing as this will not be supported as of now.
